services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    restart: unless-stopped
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3001:8000"
    depends_on:
      - peerly-frontend
      - peerly-backend

include:
  - peerly/docker-compose.ci.yml