services:
  website-backend:
    build: ./backend
    env_file:
      - ./backend/.env
    restart: unless-stopped

  website-frontend:
    build: ./frontend
    restart: unless-stopped
  
  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "3000:8000"
      - "3001:8001"
    depends_on:
      - website-backend
      - website-frontend
      - peerly-backend
      - peerly-frontend

include:
  - peerly/docker-compose.ci.yml
