version: "3.8"

services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    restart: unless-stopped
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3001:8000"