version: "3.8"

services:
  backend:
    build: ./backend
    command: "npm start"
    environment:
      - DOMAIN
      - PORT
      - DATABASE_USER
      - DATABASE_HOST
      - DATABASE_PASSWORD
      - DATABASE_PORT
      - STATIC_SITE_NAME
      - STATIC_SITE_PROTOCOL
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    command: "npm start"
    ports:
      - "3001:8000"