include:
  - peerly/docker-compose.ci.yml
  - bridge/docker-compose.ci.yml

services:
  website-backend:
    build: ./backend
    env_file:
      - ./backend/.env
    restart: unless-stopped

  website-frontend:
    build: ./frontend
    restart: unless-stopped
  
  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "3000:8000"
      - "3001:8001"
