name: Website Updater

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  Update:
    runs-on: self-hosted
    timeout-minutes: 5

    steps:
      - name: Clone repository to local
        uses: actions/checkout@v2

      - name: Rebuild containers
        run: sudo docker compose build

      - name: Run docker containers
        run: sudo docker compose up -d --env-file /opt/website/.env.prod
